export const STAGE_ENTITY = 'workspace/STAGE_ENTITY';
export const UNSTAGE_ENTITY = 'workspace/UNSTAGE_ENTITY';
export const ACTIVATE_WORKSPACE = 'workspace/ACTIVATE_WORKSPACE';
export const ACTIVE_WORKSPACE_DATA = 'workspace/ACTIVE_WORKSPACE_DATA';
export const ACTIVE_WORKSPACE_ERROR = 'workspace/ACTIVE_WORKSPACE_ERROR';
export const FETCH_AVAILABLE_WORKSPACES =
  'workspace/FETCH_AVAILABLE_WORKSPACES';
export const AVAILABLE_WORKSPACES_DATA = 'workspace/AVAILABLE_WORKSPACES_DATA';
