const test = require('/test/test-helper.xqy');
const pub = require("/lib/pubMedHelper.sjs");

let assertions = [];

const id = '/foo.xml'

const institutions = [
  "Department of Neuroscience and Pharmacology, Rudolf Magnus Institute of Neuroscience, University Medical Center Utrecht, Utrecht, The Netherlands",
  "Department of Clinical Psychology, University of Amsterdam, Amsterdam, The Netherlands",
  "Department of Neuroscience and Pharmacology, Rudolf Magnus Institute of Neuroscience, University Medical Center Utrecht, Utrecht, The Netherlands",
  "Department of Clinical Psychology, University of Amsterdam, Amsterdam, The Netherlands",
  "University of Marburg, Marburg, Germany",
  "University of Marburg, Marburg, Germany",
  "University of Marburg, Marburg, Germany",
  "Brandeis University, Boston, MA, USA",
  "University of Zurich, Zurich, Switzerland",
  "Department of Psychology, Goethe University Frankfurt, Frankfurt a. M., Germany",
  "Department of Economics, University of Heidelberg, Heidelberg, Germany",
  "Department of Psychology, University of Regensburg, Regensburg, Germany",
  "Department of Psychology, Goethe University Frankfurt, Frankfurt a. M., Germany",
  "Hospital PsiquiÁtric Universitari Institut Pere Mata de Reus, IISPV, Universitat Rovira i Virgili, Tarragona, Spain",
  "Hospital PsiquiÁtric Universitari Institut Pere Mata de Reus, IISPV, Universitat Rovira i Virgili, Tarragona, Spain",
  "Hospital PsiquiÁtric Universitari Institut Pere Mata de Reus, IISPV, Universitat Rovira i Virgili, Tarragona, Spain",
  "Hospital PsiquiÁtric Universitari Institut Pere Mata de Reus, IISPV, Universitat Rovira i Virgili, Tarragona, Spain",
  "Hospital PsiquiÁtric Universitari Institut Pere Mata de Reus, IISPV, Universitat Rovira i Virgili, Tarragona, Spain",
  "Endocrinology Unit, University/BHF Centre for Cardiovascular Science, University of Edinburgh, Edinburgh, UK",
  "Hospital PsiquiÁtric Universitari Institut Pere Mata de Reus, IISPV, Universitat Rovira i Virgili, Tarragona, Spain",
  "Endocrinology Unit, University/BHF Centre for Cardiovascular Science, University of Edinburgh, Edinburgh, UK",
  "Hospital PsiquiÁtric Universitari Institut Pere Mata de Reus, IISPV, Universitat Rovira i Virgili, Tarragona, Spain",
  "Beer-Sheva Mental Health Center, Ben-Gurion University of the Negev, Beer-Sheva, Israel",
  "The Chaim Sheba Medical Center, Tel-Aviv University, Tel-Aviv, Israel",
  "Beer-Sheva Mental Health Center, Ben-Gurion University of the Negev, Beer-Sheva, Israel",
  "Beer-Sheva Mental Health Center, Ben-Gurion University of the Negev, Beer-Sheva, Israel",
  "Institute of Behavioural Sciences, University of Helsinki, Helsinki, Finland",
  "Diabetes Prevention Unit, Department of Chronic Disease Prevention, National Institution for Health and Welfare, Helsinki, Finland",
  ", Folkhälsan Research Centre, Helsinki, Finland",
  "Unit of General Practice, Helsinki University of Central Hospital, Helsinki, Finland",
  ", Vasa Central Hospital, Vaasa, Finland",
  "Department of General Practice and Primary Health Care, University of Helsinki, Helsinki, Finland",
  "Research Programs Unit, Molecular Neurology, Biomedicum-Helsinki, University of Helsinki, Helsinki, Finland",
  "Department of Medical Genetics, Haartman Institute, Faculty of Medicine, University of Helsinki, Helsinki, Finland",
  "Diabetes Prevention Unit, Department of Chronic Disease Prevention, National Institution for Health and Welfare, Helsinki, Finland",
  "Hospital for Children and Adolescents, Helsinki University of Central Hospital, Helsinki, Finland",
  "Research Programs Unit, Molecular Neurology, Biomedicum-Helsinki, University of Helsinki, Helsinki, Finland",
  "Department of Medical Genetics, Haartman Institute, Faculty of Medicine, University of Helsinki, Helsinki, Finland",
  "Department of Mental Health and Substance Abuse Services, National Institute for Health and Welfare, Helsinki, Finland",
  "Institute of Behavioural Sciences, University of Helsinki, Helsinki, Finland",
  "Institute of Behavioural Sciences, University of Helsinki, Helsinki, Finland",
  "Institute of Behavioural Sciences, University of Helsinki, Helsinki, Finland",
  "Institute of Behavioural Sciences, University of Helsinki, Helsinki, Finland",
  "Institute of Behavioural Sciences, University of Helsinki, Helsinki, Finland",
  "Department of Medical Psychology, University Medical Center Hamburg-Eppendorf (UKE), Hamburg, Germany",
  "Institute for Biometry and Epidemiology, University Medical Center Hamburg-Eppendorf (UKE), Hamburg, Germany",
  "Institute for Neuroimmunology and Clinical Multiple Sclerosis Research (inims), University Medical Center Hamburg-Eppendorf (UKE), Hamburg, Germany",
  "Department of Medical Psychology, University Medical Center Hamburg-Eppendorf (UKE), Hamburg, Germany",
  "Institute for Neuroimmunology and Clinical Multiple Sclerosis Research (inims), University Medical Center Hamburg-Eppendorf (UKE), Hamburg, Germany",
  "Institute for Neuroimmunology and Clinical Multiple Sclerosis Research (inims), University Medical Center Hamburg-Eppendorf (UKE), Hamburg, Germany",
  "Division of Experimental Medicine, UCSF, San Francisco, USA",
  "Division of Experimental Medicine, UCSF, San Francisco, USA",
  "Center for Health and Community, UCSF, San Francisco, USA",
  "Division of Experimental Medicine, UCSF, San Francisco, USA",
  "Osher Center for Integrative Medicine, UCSF, San Francisco, USA",
  "Department of Psychiatry, UCSF, San Francisco, USA",
  "University of Florida, Gainesville, FL, USA",
  "Teacher's College at Columbia University, New York, NY, USA",
  "University of Florida, Gainesville, FL, USA",
  "Teacher's College at Columbia University, New York, NY, USA",
  "University of Florida, Gainesville, FL, USA",
  "Teacher's College at Columbia University, New York, NY, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "University of California San Francisco, San Francisco CA, USA",
  "University of California Davis, Davis, CA, USA",
  "University of Pittsburgh Medical Center, Pittsburgh, PA, USA",
  "Veterans Affairs Center of Excellence for Stress and Mental Health, VA San Diego, CA, USA",
  "University Department of Psychiatry and Psychotherapy, Hamburg, Germany",
  "Behavioral Neuroscience Group, VU University, Amsterdam, The Netherlands",
  "Department of Psychiatry, UCSD, La Jolla, CA, USA",
  "Veterans Affairs Center of Excellence for Stress and Mental Health, VA San Diego, CA, USA",
  "University Department of Psychiatry and Psychotherapy, Hamburg, Germany",
  "Behavioral Neuroscience Group, VU University, Amsterdam, The Netherlands",
  "Department of Psychiatry, UCSD, La Jolla, CA, USA",
  "Veterans Affairs Center of Excellence for Stress and Mental Health, VA San Diego, CA, USA",
  "University Department of Psychiatry and Psychotherapy, Hamburg, Germany",
  "Behavioral Neuroscience Group, VU University, Amsterdam, The Netherlands",
  "Department of Psychiatry, UCSD, La Jolla, CA, USA",
  "Veterans Affairs Center of Excellence for Stress and Mental Health, VA San Diego, CA, USA",
  "University Department of Psychiatry and Psychotherapy, Hamburg, Germany",
  "Behavioral Neuroscience Group, VU University, Amsterdam, The Netherlands",
  "Department of Psychiatry, UCSD, La Jolla, CA, USA",
  "Veterans Affairs Center of Excellence for Stress and Mental Health, VA San Diego, CA, USA",
  "University Department of Psychiatry and Psychotherapy, Hamburg, Germany",
  "Behavioral Neuroscience Group, VU University, Amsterdam, The Netherlands",
  "Department of Psychiatry, UCSD, La Jolla, CA, USA",
  "Veterans Affairs Center of Excellence for Stress and Mental Health, VA San Diego, CA, USA",
  "University Department of Psychiatry and Psychotherapy, Hamburg, Germany",
  "Behavioral Neuroscience Group, VU University, Amsterdam, The Netherlands",
  "Department of Psychiatry, UCSD, La Jolla, CA, USA",
  "Veterans Affairs Center of Excellence for Stress and Mental Health, VA San Diego, CA, USA",
  "University Department of Psychiatry and Psychotherapy, Hamburg, Germany",
  "Behavioral Neuroscience Group, VU University, Amsterdam, The Netherlands",
  "Department of Psychiatry, UCSD, La Jolla, CA, USA",
  "Veterans Affairs Center of Excellence for Stress and Mental Health, VA San Diego, CA, USA",
  "University Department of Psychiatry and Psychotherapy, Hamburg, Germany",
  "Behavioral Neuroscience Group, VU University, Amsterdam, The Netherlands",
  "Department of Psychiatry, UCSD, La Jolla, CA, USA",
  "Veterans Affairs Center of Excellence for Stress and Mental Health, VA San Diego, CA, USA",
  "University Department of Psychiatry and Psychotherapy, Hamburg, Germany",
  "Behavioral Neuroscience Group, VU University, Amsterdam, The Netherlands",
  "Department of Psychiatry, UCSD, La Jolla, CA, USA",
  "Clinical Educational & Health Psychology, University College London, London, UK",
  "Epidemiology and Public Health, University College London, London, UK",
  "Clinical Psychology and Psychotherapy, University of Zurich, Zurich, Switzerland",
  "Clinical Educational & Health Psychology, University College London, London, UK",
  "Epidemiology and Public Health, University College London, London, UK",
  "Clinical Psychology and Psychotherapy, University of Zurich, Zurich, Switzerland",
  "Department of Psychiatry, Academic Medical Center, University of Amsterdam, Amsterdam, The Netherlands",
  "Department of Psychiatry, Academic Medical Center, University of Amsterdam, Amsterdam, The Netherlands",
  "Department of Psychiatry, Academic Medical Center, University of Amsterdam, Amsterdam, The Netherlands",
  "Department of Psychiatry, Academic Medical Center, University of Amsterdam, Amsterdam, The Netherlands",
  "Department of Psychiatry, Academic Medical Center, University of Amsterdam, Amsterdam, The Netherlands",
  "VU University Medical Center, Amsterdam, The Netherlands",
  "Department of Psychiatry, Academic Medical Center, University of Amsterdam, Amsterdam, The Netherlands",
  "Arq Psychotrauma Expert Group, Diemen, The Netherlands",
  "The Institute of Stress Medicine, Gothenburg, Sweden",
  "The Wallenberg Laboratory, Department of Molecular and Clinical Medicine, University of Gothenburg, Sweden",
  "The Wallenberg Laboratory, Department of Molecular and Clinical Medicine, University of Gothenburg, Sweden",
  "The Wallenberg Laboratory, Department of Molecular and Clinical Medicine, University of Gothenburg, Sweden",
  "Department of Psychology, Saint Louis University, St. Louis, MO, USA",
  "Department of Psychology, Saint Louis University, St. Louis, MO, USA",
  "Department of Psychology, Saint Louis University, St. Louis, MO, USA",
  "Department of Psychology, University of Michigan, Ann Arbor, MI, USA",
  "Centre for Studies on Human Stress, Fernand-Seguin Research Centre of Louis-H. Lafontaine Hospital, Montreal, QC, Canada",
  "Department of Neurology and Neurosurgery, McGill University, Montreal, QC, Canada",
  "Department of Educational and Counseling Psychology, McGill University, Montreal, QC, Canada",
  "Department of Psychology, McGill University, Montreal, QC, Canada",
  "Department of Social Work, University of Montreal, Montreal, QC, Canada",
  "Centre for Studies on Human Stress, Fernand-Seguin Research Centre of Louis-H. Lafontaine Hospital, Montreal, QC, Canada",
  "Department of Neuroscience, University of Montreal, Montreal, QC, Canada",
  "Centre for Studies on Human Stress, Fernand-Seguin Research Centre of Louis-H. Lafontaine Hospital, Montreal, QC, Canada",
  "Department of Neurology and Neurosurgery, McGill University, Montreal, QC, Canada",
  "Department of Neurology and Neurosurgery, McGill University, Montreal, QC, Canada",
  "Centre for Studies on Human Stress, Fernand-Seguin Research Centre of Louis-H. Lafontaine Hospital, Montreal, QC, Canada",
  "Department of Psychiatry, University of Montreal, Montreal, QC, Canada",
  "Centre for Studies on Human Stress, Fernand Seguin Research Centre of Louis-H. Lafontaine",
  "Department of Psychiatry, University of Montreal, Montreal, QC, Canada",
  "School of Psychoeducation, University of Montreal, Montreal, QC, Canada",
  "Department of Psychology, Ryerson University, Toronto, ON, Canada",
  "Centre for Studies on Human Stress, Fernand Seguin Research Centre of Louis-H. Lafontaine",
  "Department of Psychiatry, University of Montreal, Montreal, QC, Canada",
  "School of Psychoeducation, University of Montreal, Montreal, QC, Canada",
  "Department of Psychology, Ryerson University, Toronto, ON, Canada",
  "Centre for Studies on Human Stress, Fernand Seguin Research Centre of Louis-H. Lafontaine",
  "Department of Psychiatry, University of Montreal, Montreal, QC, Canada",
  "School of Psychoeducation, University of Montreal, Montreal, QC, Canada",
  "Department of Psychology, Ryerson University, Toronto, ON, Canada",
  "Division of Medical Pharmacology, Leiden/Amsterdam Center for Drug Research & Leiden University Medical Center, Leiden, The Netherland",
  "Current address: Department of Psychiatry - Traumatic Stress Studies Division, Mount Sinai School of Medicine, New York, NY, USA",
  "Division of Medical Pharmacology, Leiden/Amsterdam Center for Drug Research & Leiden University Medical Center, Leiden, The Netherland",
  "University of Nottingham, Nottingham, UK",
  "University of Bristol, Bristol, UK",
  "University of Nottingham, Nottingham, UK",
  "University of Bristol, Bristol, UK",
  "University of Nottingham, Nottingham, UK",
  "University of Bristol, Bristol, UK",
  "University of Nottingham, Nottingham, UK",
  "University of Bristol, Bristol, UK",
  "University of Nottingham, Nottingham, UK",
  "University of Bristol, Bristol, UK",
  "University of Nottingham, Nottingham, UK",
  "University of Bristol, Bristol, UK",
  "University of Nottingham, Nottingham, UK",
  "University of Bristol, Bristol, UK",
  "University of Nottingham, Nottingham, UK",
  "University of Bristol, Bristol, UK",
  "Psychiatry, UCSF, San Francisco, CA, USA",
  "School of Medicine, Stanford University, Stanford, CA, USA",
  "Psychology, Rutgers University, Piscataway, NJ, USA",
  "School of Public Health, UCB, Berkeley, CA, USA",
  "Psychiatry, UCSF, San Francisco, CA, USA",
  "School of Medicine, Stanford University, Stanford, CA, USA",
  "Psychology, Rutgers University, Piscataway, NJ, USA",
  "School of Public Health, UCB, Berkeley, CA, USA",
  "Psychiatry, UCSF, San Francisco, CA, USA",
  "School of Medicine, Stanford University, Stanford, CA, USA",
  "Psychology, Rutgers University, Piscataway, NJ, USA",
  "School of Public Health, UCB, Berkeley, CA, USA",
  "Psychiatry, UCSF, San Francisco, CA, USA",
  "School of Medicine, Stanford University, Stanford, CA, USA",
  "Psychology, Rutgers University, Piscataway, NJ, USA",
  "School of Public Health, UCB, Berkeley, CA, USA",
  "Psychiatry, UCSF, San Francisco, CA, USA",
  "School of Medicine, Stanford University, Stanford, CA, USA",
  "Psychology, Rutgers University, Piscataway, NJ, USA",
  "School of Public Health, UCB, Berkeley, CA, USA",
  "Psychiatry, UCSF, San Francisco, CA, USA",
  "School of Medicine, Stanford University, Stanford, CA, USA",
  "Psychology, Rutgers University, Piscataway, NJ, USA",
  "School of Public Health, UCB, Berkeley, CA, USA",
  "Psychiatry, UCSF, San Francisco, CA, USA",
  "School of Medicine, Stanford University, Stanford, CA, USA",
  "Psychology, Rutgers University, Piscataway, NJ, USA",
  "School of Public Health, UCB, Berkeley, CA, USA",
  "Psychiatry, UCSF, San Francisco, CA, USA",
  "School of Medicine, Stanford University, Stanford, CA, USA",
  "Psychology, Rutgers University, Piscataway, NJ, USA",
  "School of Public Health, UCB, Berkeley, CA, USA",
  "Psychiatry, UCSF, San Francisco, CA, USA",
  "School of Medicine, Stanford University, Stanford, CA, USA",
  "Psychology, Rutgers University, Piscataway, NJ, USA",
  "School of Public Health, UCB, Berkeley, CA, USA",
  "Department of Psychiatry and Psychotherapy, Campus Benjamin Franklin, Charité University Medicine Berlin, Berlin, Germany",
  "VA Medical Center, San Francisco, CA, USA",
  "Department of Psychiatry and Psychotherapy, Campus Benjamin Franklin, Charité University Medicine Berlin, Berlin, Germany",
  "Department of Psychiatry and Psychotherapy, Campus Benjamin Franklin, Charité University Medicine Berlin, Berlin, Germany",
  "Department of Psychiatry, Charite Medical Center, Campus Benjamin Franklin, Berlin, Germany",
  "Department of Psychosomatics, University Hospital of Hamburg UKE, Hamburg, Germany",
  "Department of Psychiatry, University Hospital of Hamburg UKE, Asklepios Fachklinik Tiefenbrunn, Germany",
  "Department of Psychiatry, Charite Medical Center, Campus Benjamin Franklin, Berlin, Germany",
  "Department of Psychosomatics, University Hospital of Hamburg UKE, Hamburg, Germany",
  "Department of Psychiatry, University Hospital of Hamburg UKE, Asklepios Fachklinik Tiefenbrunn, Germany",
  "Department of Psychiatry, Charite Medical Center, Campus Benjamin Franklin, Berlin, Germany",
  "Department of Psychosomatics, University Hospital of Hamburg UKE, Hamburg, Germany",
  "Department of Psychiatry, University Hospital of Hamburg UKE, Asklepios Fachklinik Tiefenbrunn, Germany",
  "Department of Psychiatry, Charite Medical Center, Campus Benjamin Franklin, Berlin, Germany",
  "Department of Psychosomatics, University Hospital of Hamburg UKE, Hamburg, Germany",
  "Department of Psychiatry, University Hospital of Hamburg UKE, Asklepios Fachklinik Tiefenbrunn, Germany",
  "Department of Psychiatry, Charite Medical Center, Campus Benjamin Franklin, Berlin, Germany",
  "Department of Psychosomatics, University Hospital of Hamburg UKE, Hamburg, Germany",
  "Department of Psychiatry, University Hospital of Hamburg UKE, Asklepios Fachklinik Tiefenbrunn, Germany",
  "Department of Psychiatry, Charite Medical Center, Campus Benjamin Franklin, Berlin, Germany",
  "Department of Psychosomatics, University Hospital of Hamburg UKE, Hamburg, Germany",
  "Department of Psychiatry, University Hospital of Hamburg UKE, Asklepios Fachklinik Tiefenbrunn, Germany",
  "Department of Psychiatry, Charite Medical Center, Campus Benjamin Franklin, Berlin, Germany",
  "Department of Psychosomatics, University Hospital of Hamburg UKE, Hamburg, Germany",
  "Department of Psychiatry, University Hospital of Hamburg UKE, Asklepios Fachklinik Tiefenbrunn, Germany",
  "Department of Psychiatry, Charite Medical Center, Campus Benjamin Franklin, Berlin, Germany",
  "Department of Psychosomatics, University Hospital of Hamburg UKE, Hamburg, Germany",
  "Department of Psychiatry, University Hospital of Hamburg UKE, Asklepios Fachklinik Tiefenbrunn, Germany",
  "CSIRO Food and Nutritional Sciences, Adelaide, Australia",
  "Department of Microbiology & Immunology, School of Molecular & Biomedical Sciences, University of Adelaide, Australia",
  "Black Dog Institute, University of New South Wales, Sydney, NSW, Australia",
  "CSIRO Food and Nutritional Sciences, Adelaide, Australia",
  "Centre for Research in Human Development, Concordia University, Montreal, QC, Canada",
  "Douglas Mental Health University Institute, McGill University, Montreal, QC, Canada",
  "Centre for Research in Human Development, Concordia University, Montreal, QC, Canada",
  "Douglas Mental Health University Institute, McGill University, Montreal, QC, Canada",
  "Centre for Research in Human Development, Concordia University, Montreal, QC, Canada",
  "Douglas Mental Health University Institute, McGill University, Montreal, QC, Canada",
  "Centre for Research in Human Development, Concordia University, Montreal, QC, Canada",
  "Douglas Mental Health University Institute, McGill University, Montreal, QC, Canada",
  "Department of Anesthesiology and Pain Medicine, The Armed Forces Capital Hospital, Seoul, Korea",
  "Department of Integrative Medicine, CHA Medical University, Seoul, Korea",
  "Department of Psychiatry, School of Medicine and Public Health, University of Wisconsin–Madison, Madison, WI, USA",
  "Department of Psychology, University of New Orleans, New Orleans, LA, USA",
  "Department of Psychiatry, School of Medicine and Public Health, University of Wisconsin–Madison, Madison, WI, USA",
  "Department of Psychology, University of New Orleans, New Orleans, LA, USA",
  "Department of Psychiatry, School of Medicine and Public Health, University of Wisconsin–Madison, Madison, WI, USA",
  "Department of Psychology, University of New Orleans, New Orleans, LA, USA",
  "Department of Psychiatry, School of Medicine and Public Health, University of Wisconsin–Madison, Madison, WI, USA",
  "Department of Psychology, University of New Orleans, New Orleans, LA, USA",
  "Department of Psychiatry, School of Medicine and Public Health, University of Wisconsin–Madison, Madison, WI, USA",
  "Department of Psychology, University of New Orleans, New Orleans, LA, USA",
  "University of California, San Francisco, USA",
  "University of California, Los Angeles, CA, USA",
  "University of California, San Francisco, USA",
  "University of California, Los Angeles, CA, USA",
  "University of California, San Francisco, USA",
  "University of California, Los Angeles, CA, USA",
  "University of California, San Francisco, USA",
  "University of California, Los Angeles, CA, USA",
  "University of California, San Francisco, USA",
  "University of California, Los Angeles, CA, USA",
  "University of California, San Francisco, USA",
  "University of California, Los Angeles, CA, USA",
  "Department of Psychology, Technical University of Dresden, Dresden, Germany",
  "Key Laboratory of Child Development and Learning Science (Southeast University), Ministry of Education, Research Center of Learning Science, Southeast University, Nanjing, China",
  "Department of Psychology, Technical University of Dresden, Dresden, Germany",
  "Department of Psychology, Technical University of Dresden, Dresden, Germany",
  "Department of Psychology, Technical University of Dresden, Dresden, Germany",
  "Department of Psychology, Technical University of Dresden, Dresden, Germany",
  "Kinder- und Jugendklinik, Universitätsklinikum Erlangen, Erlangen, Germany",
  "Key Laboratory of Child Development and Learning Science (Southeast University), Ministry of Education, Research Center of Learning Science, Southeast University, Nanjing, China",
  "Columbia University, New York, NY, USA",
  "University of California-San Francisco, San Francisco, CA, USA",
  "Dalhousie University, Halifax, NS, Canada",
  "Columbia University, New York, NY, USA",
  "University of California-San Francisco, San Francisco, CA, USA",
  "Dalhousie University, Halifax, NS, Canada",
  "Columbia University, New York, NY, USA",
  "University of California-San Francisco, San Francisco, CA, USA",
  "Dalhousie University, Halifax, NS, Canada",
  "Columbia University, New York, NY, USA",
  "University of California-San Francisco, San Francisco, CA, USA",
  "Dalhousie University, Halifax, NS, Canada",
  "Columbia University, New York, NY, USA",
  "University of California-San Francisco, San Francisco, CA, USA",
  "Dalhousie University, Halifax, NS, Canada",
  "Columbia University, New York, NY, USA",
  "University of California-San Francisco, San Francisco, CA, USA",
  "Dalhousie University, Halifax, NS, Canada",
  "Columbia University, New York, NY, USA",
  "University of California-San Francisco, San Francisco, CA, USA",
  "Dalhousie University, Halifax, NS, Canada",
  "Columbia University, New York, NY, USA",
  "University of California-San Francisco, San Francisco, CA, USA",
  "Dalhousie University, Halifax, NS, Canada",
  "Columbia University, New York, NY, USA",
  "University of California-San Francisco, San Francisco, CA, USA",
  "Dalhousie University, Halifax, NS, Canada",
  "Department of Biomedical Sciences, Tufts University Cummings School of Veterinary Medicine, Grafton, MA, USA",
  "School of Healthcare Science, Manchester Metropolitan University, Manchester, UK",
  "Department of Biomedical Sciences, Tufts University Cummings School of Veterinary Medicine, Grafton, MA, USA",
  "School of Healthcare Science, Manchester Metropolitan University, Manchester, UK",
  "Department of Biomedical Sciences, Tufts University Cummings School of Veterinary Medicine, Grafton, MA, USA",
  "School of Healthcare Science, Manchester Metropolitan University, Manchester, UK",
  "Department of Clinical and Physiological Psychology, University of Trier, Trier, Germany",
  "Department of Clinical and Physiological Psychology, University of Trier, Trier, Germany",
  "Department of Clinical and Physiological Psychology, University of Trier, Trier, Germany",
  "Research group Psychosomatic Rehabilitation, Charité University, & Department of Behavioral Medicine and Psychosomatics, Rehabilitation Center Seehof, Berlin, Germany",
  "Department of Clinical and Physiological Psychology, University of Trier, Trier, Germany",
  "Department of Psychology",
  "Yerkes National Primate Research Center, Emory University, Atlanta, GA, USA",
  "Department of Psychiatry and Behavioral Sciences",
  "Yerkes National Primate Research Center, Emory University, Atlanta, GA, USA",
  "Department of Psychiatry and Behavioral Sciences",
  "Yerkes National Primate Research Center, Emory University, Atlanta, GA, USA",
  "Department of Psychology",
  "Yerkes National Primate Research Center, Emory University, Atlanta, GA, USA",
  "Department of Psychiatry, University of Illinois at Chicago, Chicago, IL, USA",
  "The Core Center, Bureau of Health Services of Cook County, Chicago, IL, USA",
  "Departments of Medicine Stroger Hospital and Rush University, Chicago IL, USA",
  "Department of Psychiatry, University of Illinois at Chicago, Chicago, IL, USA",
  "Department of Medicine, University of California, San Francisco, CA, USA",
  "Departments of Clinical Medicine and Epidemiology, University of California, San Francisco, CA, USA",
  "Institute for Health Promotion & Disease Prevention Research, University of Southern California, Los Angeles, CA, USA",
  "Departments of Medicine and Epidemiology & Population Health, Albert Einstein College of Medicine, New York, NY, USA",
  "Georgetown University School of Medicine, Washington, DC, USA",
  "Department of Epidemiology, Johns Hopkins School of Public Health, Baltimore, MD, USA",
  "Department of Psychology, University of Illinois at Chicago, Chicago, IL, USA",
  "Division of Neonatology, First Affiliated Hospital of Medical School, Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Division of Neonatology, First Affiliated Hospital of Medical School, Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Division of Neonatology, First Affiliated Hospital of Medical School, Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Department of Human Anatomy and Embryology, Medical School of Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Division of Obstetrics, Hospital, Hanzhong, Shaanxi, China",
  "Division of Neonatology, First Affiliated Hospital of Medical School, Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Division of Neonatology, First Affiliated Hospital of Medical School, Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Division of Neonatology, Child and Maternity Health Hospital of Shaanxi Province, Shaanxi, China",
  "Division of Neonatology, First Affiliated Hospital of Medical School, Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Division of Neonatology, First Affiliated Hospital of Medical School, Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Division of Neonatology, First Affiliated Hospital of Medical School, Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Division of Neonatology, First Affiliated Hospital of Medical School, Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Division of Neonatology, First Affiliated Hospital of Medical School, Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Department of Human Anatomy and Embryology, Medical School of Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Division of Obstetrics, Hospital, Hanzhong, Shaanxi, China",
  "Division of Neonatology, First Affiliated Hospital of Medical School, Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Division of Obstetrics and Gynaecology, First Affiliated Hospital of Medical College, Xi'an, Shaanxi, China",
  "Division of Obstetrics and Gynaecology, Second Affiliated Hospital of Medical School, Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Division of Neonatology, First Affiliated Hospital of Medical School, Xi'an Jiaotong University, Xi'an, Shaanxi, China",
  "Departments of Obstetrics, Gynecology and Reproductive Sciences, University of California, San Francisco, CA, USA",
  "Departments of Obstetrics, Gynecology and Reproductive Sciences, University of California, San Francisco, CA, USA",
  "Department of Psychiatry, University of California, San Francisco, CA, USA",
  "Department of Psychiatry, University of California, San Francisco, CA, USA",
  "Department of Psychiatry, University of California, San Francisco, CA, USA",
  "Department of Psychiatry, University of California, San Francisco, CA, USA",
  "Department of Psychiatry, University of California, San Francisco, CA, USA",
  "Department of Psychiatry, University of California, San Francisco, CA, USA",
  "Departments of Obstetrics, Gynecology and Reproductive Sciences, University of California, San Francisco, CA, USA",
  "Department of Psychiatry, University of California, San Francisco, CA, USA",
  "Department of Psychiatry, University of California, San Francisco, CA, USA",
  "Department of Medicine, Hematology-Oncology, University of California, Los Angeles, CA, USA",
  "Division of Clinical Therapeutics, New York State Psychiatric Institute, New York, NY, USA",
  "Department of Psychiatry, College of Physicians and Surgeons of Columbia University, New York, NY, USA",
  "Division of Clinical Therapeutics, New York State Psychiatric Institute, New York, NY, USA",
  "Department of Psychiatry, College of Physicians and Surgeons of Columbia University, New York, NY, USA",
  "Division of Clinical Therapeutics, New York State Psychiatric Institute, New York, NY, USA",
  "Department of Psychiatry, College of Physicians and Surgeons of Columbia University, New York, NY, USA",
  "Division of Clinical Therapeutics, New York State Psychiatric Institute, New York, NY, USA",
  "Department of Psychiatry, College of Physicians and Surgeons of Columbia University, New York, NY, USA",
  "Division of Clinical Therapeutics, New York State Psychiatric Institute, New York, NY, USA",
  "Department of Psychiatry, College of Physicians and Surgeons of Columbia University, New York, NY, USA",
  "Division of Clinical Therapeutics, New York State Psychiatric Institute, New York, NY, USA",
  "Department of Psychiatry, College of Physicians and Surgeons of Columbia University, New York, NY, USA",
  "Division of Clinical Therapeutics, New York State Psychiatric Institute, New York, NY, USA",
  "Department of Psychiatry, College of Physicians and Surgeons of Columbia University, New York, NY, USA",
  "Division of Clinical Therapeutics, New York State Psychiatric Institute, New York, NY, USA",
  "Department of Psychiatry, College of Physicians and Surgeons of Columbia University, New York, NY, USA",
  "Division of Clinical Therapeutics, New York State Psychiatric Institute, New York, NY, USA",
  "Department of Psychiatry, College of Physicians and Surgeons of Columbia University, New York, NY, USA",
  "Center for the Study of Traumatic Stress, Department of Psychiatry, USUHS. Bethesda, MD USA",
  "Center for the Study of Traumatic Stress, Department of Psychiatry, USUHS. Bethesda, MD USA",
  "Center for the Study of Traumatic Stress, Department of Psychiatry, USUHS. Bethesda, MD USA",
  "Center for the Study of Traumatic Stress, Department of Psychiatry, USUHS. Bethesda, MD USA",
  "The active duty U.S. Army Special Operations Unit, DOD. Fort Bragg, NC, USA",
  "Center for the Study of Traumatic Stress, Department of Psychiatry, USUHS. Bethesda, MD USA",
  "Center for the Study of Traumatic Stress, Department of Psychiatry, USUHS. Bethesda, MD USA",
  "Center for the Study of Traumatic Stress, Department of Psychiatry, USUHS. Bethesda, MD USA",
  "Center for the Study of Traumatic Stress, Department of Psychiatry, USUHS. Bethesda, MD USA",
  "Center for the Study of Traumatic Stress, Department of Psychiatry, USUHS. Bethesda, MD USA",
  "Department of Psychiatry (Anxiety Disorders), Academic Medical Center, Amsterdam, Utrecht, The Netherlands",
  "Laboratory of Neuroimmunology and Developmental Origins of Disease, University Medical Center Utrecht, Utrecht, The Netherlands",
  "Research Centre for Military Mental Health, Dutch Ministry of Defence Utrecht, Utrecht, The Netherlands",
  "Research Centre for Military Mental Health, Dutch Ministry of Defence Utrecht, Utrecht, The Netherlands",
  "Department of Psychiatry, Rudolf Magnus Institute, University Medical Center Utrecht, Utrecht, The Netherlands",
  "Research Centre for Military Mental Health, Dutch Ministry of Defence Utrecht, Utrecht, The Netherlands",
  "Department of Psychiatry, Rudolf Magnus Institute, University Medical Center Utrecht, Utrecht, The Netherlands",
  "Laboratory of Neuroimmunology and Developmental Origins of Disease, University Medical Center Utrecht, Utrecht, The Netherlands",
  "Laboratory of Neuroimmunology and Developmental Origins of Disease, University Medical Center Utrecht, Utrecht, The Netherlands",
  "Clinical Psychology and Psychotherapy, University of Zurich, Zurich, Switzerland",
  "Military Academy, ETH Zurich, Zurich, Switzerland",
  "Swiss Federal Institute of Sports Magglingen SFISM, Magglingen, Switzerland",
  "Swiss Federal Institute of Sports Magglingen SFISM, Magglingen, Switzerland",
  "Swiss Federal Institute of Sports Magglingen SFISM, Magglingen, Switzerland",
  "Clinical Psychology and Psychotherapy, University of Zurich, Zurich, Switzerland",
  "Beer-Sheva Mental Health Center, Ben-Gurion University of the Negev, Beersheva, Israel",
  "The Chaim Sheba Medical Center, Tel-Aviv University, Tel-Aviv, Israel",
  "Beer-Sheva Mental Health Center, Ben-Gurion University of the Negev, Beersheva, Israel",
  "Beer-Sheva Mental Health Center, Ben-Gurion University of the Negev, Beersheva, Israel",
  "University of California, San Francisco, San Francisco, CA, USA",
  "San Francisco VA Medical Center, San Francisco, CA, USA",
  "University of California, San Francisco, San Francisco, CA, USA",
  "San Francisco VA Medical Center, San Francisco, CA, USA",
  "Massachusetts General Hospital, Charlestown, MA, USA",
  "Harvard Medical School, Charlestown, MA, USA",
  "Veterans Affairs Boston Healthcare System, Boston, MA, USA",
  "Massachusetts General Hospital, Charlestown, MA, USA",
  "Harvard Medical School, Charlestown, MA, USA",
  "New York University Langone Medical Center, New York, NY, USA",
  "University of California, San Francisco, San Francisco, CA, USA",
  "San Francisco VA Medical Center, San Francisco, CA, USA",
  "Mental Illness Research, Education, and Clinical Center (MIRECC VISN 3), James J. Peters VA Medical Center, New York, NY, USA",
  "Department of Psychiatry, Mount Sinai School of Medicine, New York, NY, USA",
  "Mental Illness Research, Education, and Clinical Center (MIRECC VISN 3), James J. Peters VA Medical Center, New York, NY, USA",
  "Mental Illness Research, Education, and Clinical Center (MIRECC VISN 3), James J. Peters VA Medical Center, New York, NY, USA",
  "Mental Illness Research, Education, and Clinical Center (MIRECC VISN 3), James J. Peters VA Medical Center, New York, NY, USA",
  "Department of Psychiatry, Mount Sinai School of Medicine, New York, NY, USA",
  "Mental Illness Research, Education, and Clinical Center (MIRECC VISN 3), James J. Peters VA Medical Center, New York, NY, USA",
  "Department of Psychiatry, Mount Sinai School of Medicine, New York, NY, USA",
  "University of California, San Francisco, CA, USA",
  "San Francisco VA Medical Center, San Francisco, CA, USA",
  "Northern California Institute on Research and Education, San Franscisco, CA, USA",
  "University of California, San Francisco, CA, USA",
  "San Francisco VA Medical Center, San Francisco, CA, USA",
  "Northern California Institute on Research and Education, San Franscisco, CA, USA",
  "University of California, San Francisco, CA, USA",
  "San Francisco VA Medical Center, San Francisco, CA, USA",
  "Northern California Institute on Research and Education, San Franscisco, CA, USA",
  "University of California, San Francisco, CA, USA",
  "San Francisco VA Medical Center, San Francisco, CA, USA",
  "Northern California Institute on Research and Education, San Franscisco, CA, USA",
  "University of California, San Francisco, CA, USA",
  "San Francisco VA Medical Center, San Francisco, CA, USA",
  "Northern California Institute on Research and Education, San Franscisco, CA, USA",
  "University of California, San Francisco, CA, USA",
  "San Francisco VA Medical Center, San Francisco, CA, USA",
  "Northern California Institute on Research and Education, San Franscisco, CA, USA",
  "University of California, San Francisco, CA, USA",
  "San Francisco VA Medical Center, San Francisco, CA, USA",
  "Northern California Institute on Research and Education, San Franscisco, CA, USA",
  "VA Puget Sound Health Care System, Seattle, WA, USA",
  "University of Washington, Seattle, WA, USA",
  "VA Puget Sound Health Care System, Seattle, WA, USA",
  "University of Washington, Seattle, WA, USA",
  "VA Puget Sound Health Care System, Seattle, WA, USA",
  "University of Washington, Seattle, WA, USA",
  "VA Puget Sound Health Care System, Seattle, WA, USA",
  "University of Washington, Seattle, WA, USA",
  "VA Puget Sound Health Care System, Seattle, WA, USA",
  "University of Washington, Seattle, WA, USA",
  "VA Puget Sound Health Care System, Seattle, WA, USA",
  "University of Washington, Seattle, WA, USA",
  "VA Puget Sound Health Care System, Seattle, WA, USA",
  "University of Washington, Seattle, WA, USA",
  "VA Puget Sound Health Care System, Seattle, WA, USA",
  "University of Washington, Seattle, WA, USA",
  "VA Puget Sound Health Care System, Seattle, WA, USA",
  "University of Washington, Seattle, WA, USA",
  "VA Puget Sound Health Care System, Seattle, WA, USA",
  "University of Washington, Seattle, WA, USA",
  "VA Puget Sound Health Care System, Seattle, WA, USA",
  "University of Washington, Seattle, WA, USA",
  "Department of Psychiatry, University of California, San Francisco, CA, USA",
  "Department of Radiology and Biomedical Imaging, University of California, San Francisco, CA, USA",
  "Center for Imaging of Neurodegenerative Diseases, San Francisco Veterans Affairs Medical Center, San Francisco, CA, USA",
  "Mental Health Service, San Francisco Veterans Affairs Medical Center, San Francisco, CA, USA",
  "Department of Psychiatry, University of California, San Francisco, CA, USA",
  "Department of Radiology and Biomedical Imaging, University of California, San Francisco, CA, USA",
  "Center for Imaging of Neurodegenerative Diseases, San Francisco Veterans Affairs Medical Center, San Francisco, CA, USA",
  "Department of Psychiatry, University of California, San Francisco, CA, USA",
  "Mental Health Service, San Francisco Veterans Affairs Medical Center, San Francisco, CA, USA",
  "TNO Netherlands Organisation for Applied Scientific Research",
  "TNO Netherlands Organisation for Applied Scientific Research",
  "Vanderbilt University, Nashville, TN, USA",
  "Philips Research",
  "Tilburg University, The Netherlands",
  "Philips Research",
  "Tilburg University, The Netherlands",
  "Dutch Ministry of Defense, Department Military Mental Health, Utrecht, The Netherlands"
]
const pubOut = fn.head(pub.getAuthorsXML2(id));
const authors = pubOut.xpath('./author/institutions/institution/normalize-space(.)').toArray();

assertions.push(
  test.assertEqual(institutions.length, authors.length),
  test.assertEqual(institutions.sort(), authors.sort())
)
assertions
